development:
  adapter: postgresql
  encoding: unicode
  database: makers_bnb
  pool: 1
  username: ENV['USER']

production:
  adapter: postgresql
  encoding: unicode
  pool: 1
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>